-- =========================================
-- LAB 2: WEATHER ANALYTICS - TABLE SETUP
-- =========================================

USE WAREHOUSE GROUNDHOG_QUERY_WH;
USE DATABASE USER_DB_GROUNDHOG;
CREATE SCHEMA IF NOT EXISTS SCHEMA_WEATHER;
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

USE SCHEMA SCHEMA_WEATHER;

-- 1. RAW OPEN METEO JSON TABLE
CREATE OR REPLACE TABLE OPEN_METEO_RAW (
    INGEST_ID STRING,
    INGEST_TS_UTC TIMESTAMP_NTZ,
    LOCATION_NAME STRING,
    LAT FLOAT,
    LON FLOAT,
    API_URL STRING,
    RESPONSE_JSON VARIANT
);

-- 2. TRANSFORMED HOURLY WEATHER TABLE
CREATE OR REPLACE TABLE WEATHER_OBSERVATION_HOURLY (
    LOCATION_NAME STRING,
    OBS_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    TEMP_C FLOAT,
    REL_HUMIDITY_PCT FLOAT,
    WIND_SPEED_MS FLOAT,
    PRECIP_MM FLOAT,
    LOAD_TS_UTC TIMESTAMP_NTZ
);

-- 3. DAILY AGGREGATED WEATHER TABLE
CREATE OR REPLACE TABLE WEATHER_DAILY (
    LOCATION_NAME STRING,
    DATE DATE,
    TEMP_MAX FLOAT,
    TEMP_MIN FLOAT,
    TEMP_MEAN FLOAT,
    PRECIP_TOTAL FLOAT,
    WIND_SPEED_AVG FLOAT,
    LOAD_TS_UTC TIMESTAMP_NTZ
);

-- 4. FORECAST OUTPUT TABLE
CREATE OR REPLACE TABLE FORECAST_OUTPUT (
    FORECAST_TS_UTC TIMESTAMP_NTZ,
    ISSUED_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    PRED_TEMP_C FLOAT,
    MODEL_NAME STRING,
    MODEL_VERSION STRING,
    LOAD_TS_UTC TIMESTAMP_NTZ
);

-- 5. FINAL UNION TABLE
CREATE OR REPLACE TABLE WEATHER_FINAL (
    EVENT_TS_UTC TIMESTAMP_NTZ,
    LAT FLOAT,
    LON FLOAT,
    TEMP_C FLOAT,
    PRED_TEMP_C FLOAT,
    RECORD_TYPE STRING,
    LOAD_TS_UTC TIMESTAMP_NTZ
);

SHOW TABLES IN SCHEMA USER_DB_GROUNDHOG.SCHEMA_WEATHER;