USE ROLE TRAINING_ROLE;
USE WAREHOUSE GROUNDHOG_QUERY_WH;
USE DATABASE USER_DB_GROUNDHOG;
USE SCHEMA SCHEMA_WEATHER;

-- Create a permanent staging table with the same structure as the raw table.
-- Do this OUTSIDE the ETL transaction.
CREATE TABLE IF NOT EXISTS OPEN_METEO_RAW_STG LIKE OPEN_METEO_RAW;