USE WAREHOUSE GROUNDHOG_QUERY_WH;
USE DATABASE USER_DB_GROUNDHOG;
USE SCHEMA SCHEMA_WEATHER;

BEGIN;

DELETE FROM WEATHER_FINAL;

INSERT INTO WEATHER_FINAL
SELECT 
    OBS_TS_UTC AS EVENT_TS_UTC,
    LAT,
    LON,
    TEMP_C,
    NULL AS PRED_TEMP_C,
    'OBS' AS RECORD_TYPE,
    CURRENT_TIMESTAMP() AS LOAD_TS_UTC
FROM WEATHER_OBSERVATION_HOURLY

UNION ALL

SELECT
    FORECAST_TS_UTC AS EVENT_TS_UTC,
    LAT,
    LON,
    NULL AS TEMP_C,
    PRED_TEMP_C,
    'FCST' AS RECORD_TYPE,
    CURRENT_TIMESTAMP() AS LOAD_TS_UTC
FROM FORECAST_OUTPUT;

COMMIT;
